context:
  version: 1.7.2

package:
  name: heatseeker
  version: ${{ version }}

source:
  url: https://github.com/rschmitt/heatseeker/archive/v${{ version }}.tar.gz
  sha256: ef3b34d145423307b50382df4ce12c663ff2710b0e37edfe242a671aa1c563f6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - hs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A high-performance Selecta clone, written in Rust
  homepage: https://github.com/rschmitt/heatseeker
  repository: https://github.com/rschmitt/heatseeker

extra:
  recipe-maintainers:
    - danielnachun
