context:
  version: "1.10.0"

package:
  name: heatseeker
  version: ${{ version }}

source:
  url: https://github.com/rschmitt/heatseeker/archive/v${{ version }}.tar.gz
  sha256: 37029e2c70bd2afb21a4d1b49b4d6ea151b4415d22a292a7cd0bcbac3449b1b3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - libgit2  # only used for a build binary
    - pkg-config

tests:
  - script:
      - hs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A high-performance Selecta clone, written in Rust
  homepage: https://github.com/rschmitt/heatseeker
  repository: https://github.com/rschmitt/heatseeker

extra:
  recipe-maintainers:
    - danielnachun
