context:
  version: "1.8.0"

package:
  name: heatseeker
  version: ${{ version }}

source:
  url: https://github.com/rschmitt/heatseeker/archive/v${{ version }}.tar.gz
  sha256: 4d6b5f96ebb2b0337d0bbb8476691e8556bdb82accedc4af23080ed98cd862f8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - hs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A high-performance Selecta clone, written in Rust
  homepage: https://github.com/rschmitt/heatseeker
  repository: https://github.com/rschmitt/heatseeker

extra:
  recipe-maintainers:
    - danielnachun
