context:
  version: "1.10.1"

package:
  name: heatseeker
  version: ${{ version }}

source:
  url: https://github.com/rschmitt/heatseeker/archive/v${{ version }}.tar.gz
  sha256: 79c6bdcb19c68a958ff368d3c20c9ec108d5e975736b8334cad04d383d96c7d1

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - libgit2  # only used for a build binary
    - pkg-config
  host:
    - if: ppc64le
      then: zlib

tests:
  - script:
      - hs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A high-performance Selecta clone, written in Rust
  homepage: https://github.com/rschmitt/heatseeker
  repository: https://github.com/rschmitt/heatseeker

extra:
  recipe-maintainers:
    - danielnachun
